/**
 * The generated workspace's container artifacts: one parameterized Dockerfile and
 * a Compose stack covering every member plus the transport's backing service.
 *
 * M39 owns this repository's OWN deployment objects — `docker/Dockerfile` builds
 * an example under `apps/`, the Helm chart deploys one. Nothing generated anything
 * into a user's project, so a scaffolded workspace with three services and a Redis
 * transport left a developer hand-writing every one of these files, against a
 * README that named a broker endpoint nothing served.
 *
 * The Compose file is {@linkcode GeneratedFile.managed} and regenerated on every
 * `setu generate app`, for the same reason each member's discovery module is: the
 * port a member binds and the port the stack publishes are one datum, and a stack
 * that names two of the three members is worse than none.
 *
 * Five details here are M39's findings rather than choices, and each one was a
 * real failure there:
 *
 * - **The build context is the workspace root.** A member's `deno.json` is
 *   discovered as a workspace member, and the root manifest is what makes the glob
 *   resolve; a context of the member directory alone drops it.
 * - **The base image tag is pinned.** A base older than the Deno that wrote the
 *   committed lockfile fails with `Unsupported lockfile version`, and a floating
 *   tag makes that arrive on an unrelated day.
 * - **`USER` is NUMERIC.** Kubernetes' `runAsNonRoot: true` refuses an image
 *   declaring a non-numeric user (`cannot verify user is non-root`) while Docker
 *   resolves the name happily — so a named user fails only once deployed.
 * - **Permissions are explicit, not `-A`.** The set mirrors the member's own
 *   generated `start` task.
 * - **`stop_grace_period` is honoured** because the generated entry installs a
 *   SIGTERM handler. Without one the window is decorative: the process dies from
 *   the signal in milliseconds.
 *
 * @module
 */

import type { GeneratedFile } from '../utils/file-writer.ts';
import { hostVariable } from './discovery-module.ts';
import { MEMBERS_DIR, type WorkspaceManifest } from './manifest.ts';
import type { TransportSpec } from './transport.ts';

/** Where the workspace's container artifacts live, relative to its root. */
export const DOCKER_DIR = 'docker';

/** The generated Compose file's path, relative to the workspace root. */
export const COMPOSE_FILE = `${DOCKER_DIR}/compose.yaml`;

/** The generated Dockerfile's path, relative to the workspace root. */
export const DOCKERFILE = `${DOCKER_DIR}/Dockerfile`;

/**
 * The Deno image the generated Dockerfile builds on.
 *
 * Pinned deliberately — see this module's own notes. Bumping it is a one-line
 * change because both the Dockerfile and the Compose file read it from here.
 */
const DENO_IMAGE = 'denoland/deno:alpine-2.9.5';

/**
 * The numeric uid the `denoland/deno` image's own `deno` user has.
 *
 * Named `deno` in that image; written as a number because Kubernetes cannot
 * verify a named user is non-root.
 */
const DENO_UID = '1000';

/**
 * Builds the workspace's Dockerfile.
 *
 * One file for every member, selected with `--build-arg MEMBER=<name>`, rather
 * than one per member: AI_GUIDELINES §11.1, and it is what keeps a workspace's
 * tenth service from needing a tenth near-identical file.
 *
 * @returns The Dockerfile contents
 */
function dockerfile(): string {
  return `# Generated by \`setu\`. Builds ANY member of this workspace:
#
#   docker build -f ${DOCKERFILE} --build-arg MEMBER=orders -t orders .
#
# The build context MUST be the workspace root (note the trailing \`.\`). A member's
# deno.json is resolved as a workspace member, and the root manifest is what makes
# the glob resolve — a context of the member directory alone drops it.
#
# The tag is pinned, not floating: a Deno older than the one that wrote deno.lock
# fails with \`Unsupported lockfile version\`, and a floating tag makes that failure
# arrive on a day you changed nothing.
FROM ${DENO_IMAGE}

# Which member to build. Redeclared after FROM because an ARG before the first
# FROM is visible only to FROM lines.
ARG MEMBER

WORKDIR /srv

# The root manifest and lockfile first: they change far less often than member
# source, so they earn their own cache layer.
COPY deno.json* deno.lock* ./

# Then only the selected member. Copying all of ${MEMBERS_DIR}/ would invalidate
# this layer whenever any unrelated member changed.
COPY ${MEMBERS_DIR}/\${MEMBER} ./${MEMBERS_DIR}/\${MEMBER}

WORKDIR /srv/${MEMBERS_DIR}/\${MEMBER}

# Resolve the whole module graph at build time, so the container starts without
# reaching the network for its own dependencies.
RUN deno cache main.ts

# The cache written above lives in DENO_DIR and must stay readable to the user the
# container runs as.
RUN chown -R ${DENO_UID}:${DENO_UID} /srv /deno-dir

# NUMERIC, not \`USER deno\`: Kubernetes' runAsNonRoot refuses an image whose user
# is a name — "cannot verify user is non-root" — while Docker resolves it happily,
# so a named user fails only once deployed.
USER ${DENO_UID}:${DENO_UID}

# No EXPOSE: every member binds a DIFFERENT port, allocated by the CLI and read
# from its own generated discovery module, so there is no one number this
# parameterized file could name. The Compose stack publishes each member's port.

# Explicit permissions rather than \`-A\`: this is a security-focused framework and
# an image should not hand its process every capability. The set mirrors the
# member's own generated \`start\` task, plus \`--allow-sys\` for the hostname and
# platform probes the health and metrics plugins make.
CMD ["run", "--allow-net", "--allow-env", "--allow-read", "--allow-sys", "main.ts"]
`;
}

/**
 * The environment one member needs to reach everything else in a cluster.
 *
 * Shared by the Compose stack and the Kubernetes objects, because the answer is
 * the same in both and for the same reason: a sibling is reachable by its SERVICE
 * NAME, never by the loopback address the generated map falls back to. Two copies
 * of this would let one deployment target keep working while the other silently
 * routed every request into the caller's own container.
 *
 * @param siblings - Every OTHER member of the workspace
 * @param transport - The workspace's transport
 * @returns Variable → value
 */
export function memberEnvironment(
  siblings: readonly WorkspaceManifest['members'][number][],
  transport: TransportSpec,
): Readonly<Record<string, string>> {
  return {
    ...Object.fromEntries(siblings.map((sibling) => [hostVariable(sibling.name), sibling.name])),
    ...transport.compose?.memberEnv,
  };
}

/**
 * Renders one member's Compose service.
 *
 * The container listens on the member's OWN allocated port and publishes it
 * unchanged, so one number describes the service everywhere: what it binds, what
 * the host reaches it on, and what every sibling's discovery map names. Remapping
 * to a fixed container port would need the entry to read a `PORT` variable it does
 * not read.
 *
 * @param name - The member's directory name
 * @param port - The port it binds
 * @param siblings - Every other member, whose host variables this service sets
 * @param transport - The workspace's transport, read for its backing service
 * @returns The service definition, indented for Compose's `services:` key
 */
function memberService(
  name: string,
  port: number,
  siblings: readonly WorkspaceManifest['members'][number][],
  transport: TransportSpec,
): string {
  const backing = transport.compose;

  // Each sibling by SERVICE NAME. Without these the member's generated map falls
  // back to loopback, which inside a container is the member itself.
  const envLines = Object.entries(memberEnvironment(siblings, transport))
    .map(([key, value]) => `      ${key}: '${value}'`)
    .join('\n');

  const dependsOn = backing?.dependsOn ?? [];
  const dependsBlock = dependsOn.length === 0 ? '' : `
    depends_on:
${
    dependsOn.map((service) => `      ${service}:\n        condition: ${backing?.condition}`)
      .join('\n')
  }`;

  return `  ${name}:
    build:
      context: ..
      dockerfile: ${DOCKERFILE}
      args:
        MEMBER: ${name}
    ports:
      - '${port}:${port}'
    environment:
${envLines}${dependsBlock}
    # The messaging plugin connects to its broker during plugin registration and
    # does not retry, so a member that loses the race to a backing service whose
    # image cannot be health-probed exits. Compose brings it back until the broker
    # answers.
    restart: unless-stopped
    # Honoured because the generated entry installs a SIGTERM handler; without one
    # the process dies from the signal in milliseconds and this window is
    # decorative.
    stop_grace_period: 30s
`;
}

/**
 * Builds the container artifacts for a workspace.
 *
 * The Compose file lists every member, so it is regenerated on each
 * `generate app` exactly as the discovery modules are — and is `managed` for the
 * same reason: the CLI owns it, and refusing to overwrite it would make the second
 * member fail.
 *
 * @param manifest - The workspace as it will be after the current command
 * @param transport - The workspace's transport
 * @returns The files to write, relative to the workspace root
 */
export function workspaceContainerFiles(
  manifest: WorkspaceManifest,
  transport: TransportSpec,
): readonly GeneratedFile[] {
  const backing = transport.compose;

  // Sorted, so a manifest a human has reordered does not turn a no-op
  // regeneration into a diff — the same reason the discovery map sorts.
  const members = [...manifest.members].sort((left, right) =>
    left.name < right.name ? -1 : left.name > right.name ? 1 : 0
  );

  const services = members
    .map((member) =>
      memberService(
        member.name,
        member.port,
        members.filter((other) => other.name !== member.name),
        transport,
      )
    )
    .join('\n');

  const compose = `# Generated by \`setu generate app\`.
# The CLI owns this file and rewrites it whenever a member is added, so edits here
# are lost — the member list and the ports come from setu.workspace.json.
#
#   docker compose -f ${COMPOSE_FILE} up --build
#
# This is the LOCAL topology. A deployed one uses a real registry, a real service
# discovery backend (\`provider: 'consul'\`, \`'kubernetes'\`, \`'dns'\`), and the
# Kubernetes objects under k8s/.

name: ${'${COMPOSE_PROJECT_NAME:-setu-workspace}'}

services:
${services}${backing === undefined ? '' : `\n${backing.services}`}`;

  return [
    { path: DOCKERFILE, contents: dockerfile(), managed: true },
    { path: COMPOSE_FILE, contents: compose, managed: true },
    ...(backing?.files ?? []).map((file) => ({ ...file, managed: true })),
  ];
}
