/**
 * The per-member discovery module — how a workspace member learns its siblings.
 *
 * This is M58's mechanism applied to a CROSS-FILE write: a module the CLI owns
 * outright, which the member's `setu.config.ts` and `main.ts` already import, so
 * adding a service registers it with its callers without editing anything the
 * developer wrote. Every member's copy is regenerated on every
 * `setu generate app`.
 *
 * The map is honest in a way M50b's would not have been. That milestone wired
 * `ServiceDiscoveryPlugin({ provider: 'static', services: {} })` into the
 * microservice template with a deliberately EMPTY map, because a sample entry
 * would name an instance at a dead port. Here the sibling exists in this same
 * repository and its port was allocated by the same command, so the entry
 * resolves to something that is actually there.
 *
 * @module
 */

import { CONFIG_MODULE } from '../constants.ts';
import type { WorkspaceMember } from './manifest.ts';

/** The module's path, relative to a member's own root. */
export const DISCOVERY_MODULE = 'src/discovery/services.ts';

/** The specifier a member's own modules import {@linkcode DISCOVERY_MODULE} by. */
export const DISCOVERY_SPECIFIER = `./${DISCOVERY_MODULE}`;

/** The exported constant carrying the member's own port. */
export const SERVICE_PORT_EXPORT = 'SERVICE_PORT';

/** The exported constant carrying every sibling's address. */
export const SERVICE_ENDPOINTS_EXPORT = 'SERVICE_ENDPOINTS';

/**
 * The host every generated endpoint names.
 *
 * The members run on one machine during development, and that is the only
 * topology the CLI can know. A deployed topology comes from a real provider arm
 * (`consul`, `kubernetes`, `dns`), not from this file.
 */
const LOCAL_HOST = '127.0.0.1';

/**
 * Renders one member's discovery module.
 *
 * `SERVICE_ENDPOINTS` deliberately EXCLUDES the member itself: discovery is for
 * reaching other services, and a self-entry invites a service to route a
 * request back into its own process. Sibling keys are sorted, because the
 * caller's member order comes from a manifest a human may reorder, and an
 * unsorted map would turn a no-op regeneration into a diff.
 *
 * Both constants are emitted for every member, including one whose plugin set
 * has no service discovery: `main.ts` reads the port on every member, and a
 * member that gains the plugin later needs no shape change here.
 *
 * @param member - The member this module belongs to
 * @param all - Every member of the workspace, including `member`
 * @returns The module contents
 */
export function renderDiscoveryModule(
  member: WorkspaceMember,
  all: readonly WorkspaceMember[],
): string {
  // Plain `.sort()`, like every other determinism sort in this package
  // (`seamNames`, `readArtifactNames`, `readModuleNames`). `localeCompare`
  // would order by the collation of whatever locale the machine happens to run
  // under, which is the opposite of the property this sort exists for.
  const siblings = all
    .filter((other) => other.name !== member.name)
    .map((other) => other.name)
    .sort();

  const portOf = new Map(all.map((other) => [other.name, other.port]));
  const entries = siblings
    .map((name) => `  '${name}': [{ host: '${LOCAL_HOST}', port: ${portOf.get(name)} }],\n`)
    .join('');

  const endpoints = entries === '' ? '{}' : `{\n${entries}}`;

  return `// Generated by \`setu generate app\`.
// The CLI owns this file and rewrites it whenever a workspace member is added,
// so edits here are lost — add them with the CLI.
//
// \`${CONFIG_MODULE}\` consumes it as:
//
//   import { ${SERVICE_ENDPOINTS_EXPORT} } from '${DISCOVERY_SPECIFIER}';
//   ServiceDiscoveryPlugin({ provider: 'static', services: ${SERVICE_ENDPOINTS_EXPORT} })
//
// \`main.ts\` consumes it as:
//
//   import { ${SERVICE_PORT_EXPORT} } from '${DISCOVERY_SPECIFIER}';
//   await app.start({ port: ${SERVICE_PORT_EXPORT} });
//
// This is the LOCAL development topology — the addresses your workspace members
// bind on this machine. A deployed topology comes from a real discovery backend
// (\`provider: 'consul'\`, \`'kubernetes'\`, \`'dns'\`), not from this file.

/** The port this workspace member binds. */
export const ${SERVICE_PORT_EXPORT} = ${member.port};

/** Every OTHER member of this workspace, by service name. */
export const ${SERVICE_ENDPOINTS_EXPORT} = ${endpoints};
`;
}
