/**
 * The proto toolchain a `--transport grpc` member needs to serve its OWN service.
 *
 * A bare `GrpcPlugin()` already answers `grpc.health.v1.Health/Check` with no
 * configuration, because the plugin carries that descriptor itself. Serving an
 * application's own protos is different: `grpc.addService` takes a **Protobuf-ES
 * descriptor**, which only a proto compiler can produce, and this CLI has no
 * dependencies and cannot be one. That is why it was out of scope.
 *
 * What closes it is emitting the toolchain rather than being it — and the reason
 * that works at all was **measured**, not assumed:
 *
 * - `deno run -A npm:@bufbuild/buf --version` → `1.72.0`. The buf CLI runs under
 *   Deno's npm compatibility.
 * - `buf generate` with a plugin declared as `local: protoc-gen-es` FAILS —
 *   `exec: "protoc-gen-es": executable file not found in $PATH`, because nothing
 *   installs a PATH binary. Declaring the plugin as a COMMAND
 *   (`local: ['deno', 'run', '-A', 'npm:@bufbuild/protoc-gen-es@^2']`) works, and
 *   produced `src/gen/orders/v1/orders_pb.ts` exporting the `GenService`
 *   descriptor `addService` takes.
 *
 * So the generated project needs no `buf` on the developer's PATH, no `protoc`, and
 * no global install: one `deno task proto:gen`. A **remote** plugin
 * (`remote: buf.build/bufbuild/es`) would also have worked and was rejected — it
 * uploads the schema to a registry to compile it, which is a surprising thing for a
 * scaffold to arrange on a developer's behalf.
 *
 * @module
 */

import type { GeneratedFile } from '../utils/file-writer.ts';

/** The task that regenerates descriptors from the project's protos. */
export const PROTO_TASK = 'proto:gen';

/** Where the generated descriptors land, relative to the member root. */
export const PROTO_OUT_DIR = 'src/gen';

/** Where a member's `.proto` files live. */
export const PROTO_DIR = 'proto';

/**
 * The command the `proto:gen` task runs.
 *
 * `buf` through Deno rather than a PATH binary, for the reason in this module's
 * notes. `-A` because buf reads and writes the project tree and fetches its own
 * platform binary on first use.
 */
export const PROTO_TASK_COMMAND = 'deno run -A npm:@bufbuild/buf@^1.57 generate';

/**
 * The import-map entries a member needs to compile what `proto:gen` writes.
 *
 * Found by running the task and then trying to USE the file: a generated
 * descriptor imports `@bufbuild/protobuf/codegenv2`, and without these the member
 * fails with `Import "@bufbuild/protobuf/codegenv2" not a dependency and not in
 * import map` — a toolchain that emits source the project cannot compile.
 *
 * BOTH entries are required. A bare specifier mapping does not cover subpaths, so
 * the trailing-slash form is what resolves `/codegenv2`; the bare one is what a
 * hand-written `import { create } from '@bufbuild/protobuf'` needs.
 */
export const PROTO_IMPORTS: Readonly<Record<string, string>> = {
  '@bufbuild/protobuf': 'npm:@bufbuild/protobuf@^2',
  '@bufbuild/protobuf/': 'npm:/@bufbuild/protobuf@^2/',
};

/**
 * Builds the toolchain files.
 *
 * @param packageName - The proto package, e.g. `orders.v1`
 * @returns The files to create, relative to the member root
 */
export function protoToolchainFiles(packageName: string): readonly GeneratedFile[] {
  const directory = packageName.replaceAll('.', '/');

  const proto = `syntax = "proto3";

package ${packageName};

// Replace this with the service this member actually serves. Every change here
// needs \`deno task ${PROTO_TASK}\` before it reaches ${PROTO_OUT_DIR}/.

message PingRequest {
  string note = 1;
}

message PingResponse {
  string note = 1;
}

service PingService {
  rpc Ping(PingRequest) returns (PingResponse);
}
`;

  // v2 of both files: v1 keys (`directories`, `plugins[].plugin`) are accepted but
  // deprecated, and mixing versions between the two is the most common way a buf
  // setup fails with a message about neither.
  const bufYaml = `version: v2
modules:
  - path: ${PROTO_DIR}
`;

  const bufGenYaml = `# Generated by \`setu\`. Run: deno task ${PROTO_TASK}
#
# The plugin is declared as a COMMAND, not as a name. buf resolves
# \`local: protoc-gen-es\` on \$PATH, and nothing here installs a PATH binary —
# measured: "exec: \\"protoc-gen-es\\": executable file not found in \$PATH". Running
# it through Deno needs no install of any kind.
#
# A remote plugin (\`remote: buf.build/bufbuild/es\`) would also work and is
# deliberately not used: it uploads this schema to a registry to compile it.
version: v2
inputs:
  - directory: ${PROTO_DIR}
plugins:
  - local: ['deno', 'run', '-A', 'npm:@bufbuild/protoc-gen-es@^2']
    out: ${PROTO_OUT_DIR}
    opt: target=ts
`;

  const readme = `# Protos

\`\`\`bash
deno task ${PROTO_TASK}
\`\`\`

Descriptors land in \`${PROTO_OUT_DIR}/\` and are what \`grpc.addService\` takes:

\`\`\`ts
import { CAPABILITIES } from '@setu-ts/common';
import type { IGrpcService } from '@setu-ts/common';
import { PingService } from './${PROTO_OUT_DIR}/${directory}/${packageName.split('.')[0]}_pb.ts';

// Inside a plugin's register(ctx), or anywhere the registry is reachable:
const grpc = ctx.services.get<IGrpcService>(CAPABILITIES.GRPC);
grpc.addService(PingService, {
  ping: (request: { note: string }) => ({ note: request.note }),
});
\`\`\`

\`${PROTO_OUT_DIR}/\` is generated: commit it or add it to \`.gitignore\`, but do not
edit it — the next \`deno task ${PROTO_TASK}\` overwrites it.

Nothing needs \`buf\` or \`protoc\` on your PATH: both the compiler and the
TypeScript plugin run through Deno's npm compatibility.
`;

  return [
    { path: `${PROTO_DIR}/${directory}/${packageName.split('.')[0]}.proto`, contents: proto },
    { path: 'buf.yaml', contents: bufYaml },
    { path: 'buf.gen.yaml', contents: bufGenYaml },
    { path: `${PROTO_DIR}/README.md`, contents: readme },
  ];
}
