/**
 * The generated development entry — `main.dev.ts`.
 *
 * The production entry never imports this module and nothing in the production
 * graph imports the diagnostics plugin: the devtool composition exists only
 * here. The production image excludes each member's main.dev.ts through .dockerignore
 * and removes the development-only import pin before installing the remaining
 * import map and checking main.ts through --entrypoint, keeping the connector out of its cache.
 *
 * The entry READS its credentials; it never generates, writes or prints a pair.
 * The two variable names are approved CLI surface (AI_GUIDELINES §10.2): a
 * rename is a breaking change to every scaffolded project, which is why the
 * emitted warning above the reads names the other sites that must change with
 * it — the files are the developer's once written, and nothing restores them.
 *
 * @module
 */

import { DISCOVERY_SPECIFIER, SERVICE_PORT_EXPORT } from '../workspace/discovery-module.ts';
import { isUsablePort } from '../workspace/manifest.ts';
import type { EntryPort } from '../templates/project-files.ts';
import { DEVTOOL_ENTRY_MODULE, shutdownBlock } from '../templates/project-files.ts';

/**
 * The session-ID variable the generated entry reads.
 *
 * Approved CLI surface under AI_GUIDELINES §10.2 (maintainer, 2026-09-21); a
 * later rename is a breaking change to every scaffolded project.
 */
export const DEVTOOL_SESSION_ID_VARIABLE = 'SETU_DEVTOOL_SESSION_ID';

/**
 * The session-key variable the generated entry reads.
 *
 * Approved CLI surface under AI_GUIDELINES §10.2 (maintainer, 2026-09-21); a
 * later rename is a breaking change to every scaffolded project.
 */
export const DEVTOOL_SESSION_KEY_VARIABLE = 'SETU_DEVTOOL_SESSION_KEY';

/** What rendering a development entry needs. */
export interface DevEntryInput {
  /** The IPv4 loopback port the diagnostics listener binds. */
  readonly devtoolPort: number;
  /**
   * Where the application port comes from, when it is not the environment
   * default. A workspace member imports it from its generated discovery
   * module, so the port it binds and the port its siblings dial stay one
   * datum — exactly as `main.ts` does.
   */
  readonly port?: EntryPort;
}

/**
 * Renders `main.dev.ts` for a devtool-enabled project.
 *
 * Everything below the credentials is the production composition: the same
 * factory, the same startup, the same graceful-shutdown block `main.ts`
 * renders. The only additions are the credential reads (refusing to start
 * when either is absent or malformed, never printing a value), the plugin,
 * and the kernel diagnostics option the constructor requires.
 *
 * @param input - The devtool port and, for a member, the application port
 * @returns The file contents
 */
export function renderDevEntry(input: DevEntryInput): string {
  const portImport = input.port === undefined
    ? ''
    : `import { ${input.port.symbol} } from '${input.port.from}';\n`;
  const appPort = input.port === undefined
    ? "Number(runtime.env.PORT ?? '3000')"
    : input.port.symbol;

  return `// Generated by \`setu\` — the development entry for the local diagnostics
// connector. The production entry (main.ts) never imports this file, and
// nothing in the production graph imports the diagnostics plugin: the
// composition below exists only here. Run it with \`deno task dev\`; the
// launcher supplies the session credentials through the process environment.

import { createApp } from './setu.config.ts';
import { createRuntimeServices } from '@setu-ts/runtime';
import { CAPABILITIES } from '@setu-ts/common';
import type { ILogger, IPlugin } from '@setu-ts/common';
import { DiagnosticsPlugin } from '@setu-ts/diagnostics-plugin';
${portImport}
const runtime = createRuntimeServices();

// The two variable names read below are a contract with the devtool launcher.
// Renaming or removing either one stops the devtool connecting, and the error
// will not say why. In a workspace the same names are read by scripts/dev.ts
// and granted to that runner's --allow-env list in the root deno.json —
// change those sites together.
const sessionId = Deno.env.get('${DEVTOOL_SESSION_ID_VARIABLE}');
const rawSessionKey = Deno.env.get('${DEVTOOL_SESSION_KEY_VARIABLE}');

if (sessionId === undefined || /^[0-9a-f]{32}$/.test(sessionId) === false) {
  console.error(
    'setu devtool: ${DEVTOOL_SESSION_ID_VARIABLE} is absent or malformed (expected 32 lowercase' +
      ' hex characters, fresh per launch). The connector did not start.',
  );
  Deno.exit(1);
}
if (rawSessionKey === undefined || /^[0-9a-f]{64}$/.test(rawSessionKey) === false) {
  console.error(
    'setu devtool: ${DEVTOOL_SESSION_KEY_VARIABLE} is absent or malformed (expected 32 bytes as' +
      ' 64 lowercase hex characters, fresh per launch). The connector did not start.',
  );
  Deno.exit(1);
}

const sessionKey = new Uint8Array(32);
for (let index = 0; index < 32; index++) {
  sessionKey[index] = Number.parseInt(rawSessionKey.slice(index * 2, index * 2 + 2), 16);
}

const diagnostics = DiagnosticsPlugin({
  enabled: true,
  port: ${input.devtoolPort}, // IPv4 loopback only; the listener refuses any other hostname
  sessionId,
  sessionKey,
  maxSessionLifetimeMs: 28_800_000,
});

let devtoolRegistered = false;
const devtoolProbe: IPlugin = {
  name: 'setu-devtool-probe',
  version: '0.0.0',
  register() {
    devtoolRegistered = true;
  },
};

const app = await createApp(undefined, {
  plugins: [diagnostics, devtoolProbe],
  diagnostics: {},
});

await app.start({ port: ${appPort} });
if (!devtoolRegistered || app.diagnostics === undefined) {
  console.error(
    'setu devtool: setu.config.ts did not pass the devtool composition to createApplication — ' +
      'the connector is not running. Re-run \`setu devtool enable\`, which names the two lines to add.',
  );
  await app.stop();
  Deno.exit(1);
}
${shutdownBlock('deno')}`;
}

/** The module path of the generated development entry, relative to a project root. */
export { DEVTOOL_ENTRY_MODULE };

/** The formatted rendering and previous compact rendering of a CLI-owned entry. */
export function devEntryVariants(devtoolPort: number, member = true): readonly string[] {
  const raw = renderDevEntry({
    devtoolPort,
    ...(member ? { port: { symbol: SERVICE_PORT_EXPORT, from: DISCOVERY_SPECIFIER } } : {}),
  });
  return [
    raw,
    raw.replace(
      '  register() {\n    devtoolRegistered = true;\n  },',
      '  register() { devtoolRegistered = true; },',
    ),
  ];
}

/** Reads the port only from a complete, unedited CLI-owned entry. */
export function devEntryPort(source: string, member = false): number | undefined {
  const match = /\n {2}port: ([0-9]+), \/\/ IPv4 loopback only;/.exec(source);
  const port = Number(match?.[1]);
  return isUsablePort(port) && devEntryVariants(port, member).includes(source) ? port : undefined;
}
