/**
 * Migration schematic (gated on `database-plugin`).
 *
 * Not a framework seam, and that reason is unchanged: nothing in the framework
 * reads migration files, no plugin calls `ctx.cli.register`, and there is no
 * `setu db:migrate` to register into. Fabricating a registration site for a
 * consumer that does not exist would be worse than saying so.
 *
 * What DID change (D5) is that the emitted migration is no longer an orphan.
 * The one schematic gated on `database-plugin` produced a file nothing imported
 * and nothing could run, so every project that used it hand-wrote the same
 * `src/migrations/run.ts`. That runner is now generated, alongside a managed
 * barrel listing every migration in order — project-local, exactly as the
 * hand-written one was, so the framework claim above stays true.
 *
 * @module
 */

import type { DerivedNames, GeneratedFile, SchematicOptions } from './registry.ts';
import { MIGRATIONS_DIR } from '../utils/migration-scanner.ts';
import { PROGRAM_NAME } from '../constants.ts';

/**
 * Formats an epoch-milliseconds reading as a `YYYYMMDDHHMMSS` UTC stamp.
 *
 * @param epochMs - Wall-clock milliseconds
 * @returns The 14-character timestamp used to order migrations
 */
function stamp(epochMs: number): string {
  const date = new Date(epochMs);
  const pad = (value: number, width = 2) => String(value).padStart(width, '0');
  return [
    pad(date.getUTCFullYear(), 4),
    pad(date.getUTCMonth() + 1),
    pad(date.getUTCDate()),
    pad(date.getUTCHours()),
    pad(date.getUTCMinutes()),
    pad(date.getUTCSeconds()),
  ].join('');
}

/**
 * Generates a timestamped migration.
 *
 * The timestamp comes from `options.now()` — the injected clock — so the
 * emitted filename is deterministic under test and never reads a runtime API
 * directly.
 *
 * @param names - Naming forms derived from the user's input
 * @param options - Supplies the clock for the filename timestamp, and the
 * migrations already present, for the barrel
 * @returns The migration, plus the managed barrel and runner
 */
export function generateMigration(
  names: DerivedNames,
  options: SchematicOptions,
): readonly GeneratedFile[] {
  const contents = `import type { Migration } from './run.ts';

/**
 * Migration: ${names.kebab}
 *
 * Applied in filename order — the leading timestamp is what orders it. \`down\`
 * must exactly reverse \`up\`.
 *
 * Registered through the generated \`index.ts\` beside this file, which
 * \`run.ts\` applies — so this needs no further wiring. The framework itself
 * ships no migration runner: \`run.ts\` is this project's, though the CLI owns
 * and rewrites it. This migration is yours.
 *
 * The export is named \`migration\` rather than after the file, because the
 * generated barrel imports it by that fixed name.
 */
export const migration: Migration = {
  async up(): Promise<void> {
    // Replace with the forward change.
    await Promise.resolve();
  },

  async down(): Promise<void> {
    // Replace with the exact inverse of up().
    await Promise.resolve();
  },
};
`;
  const file = `${stamp(options.now())}-${names.kebab}`;
  // Union rather than append, so regenerating over an existing migration lists
  // it exactly once — the same idempotence every seam barrel has.
  const all = [...new Set([...(options.migrations ?? []), file])].sort();

  return [
    { path: `${MIGRATIONS_DIR}/${file}.ts`, contents },
    { path: `${MIGRATIONS_DIR}/index.ts`, contents: renderBarrel(all), managed: true },
    { path: `${MIGRATIONS_DIR}/run.ts`, contents: RUNNER, managed: true },
  ];
}

/**
 * Renders the managed barrel listing every migration in application order.
 *
 * Filename order IS application order: the leading timestamp orders it, and a
 * plain sort over a fixed-width numeric prefix is chronological.
 *
 * @param files - Migration file names, without the `.ts` suffix, oldest first
 * @returns The barrel contents
 */
function renderBarrel(files: readonly string[]): string {
  const imports = files
    .map((file, index) => `import { migration as m${index} } from './${file}.ts';`)
    .join('\n');
  const entries = files
    .map((file, index) => `  { name: '${file}', migration: m${index} },`)
    .join('\n');

  return `// Generated by \`${PROGRAM_NAME} generate migration\`.
// The CLI owns this file and rewrites it whenever a migration is added, so edits
// here are lost — add them with the CLI.

import type { Migration } from './run.ts';

${imports}

/** Every migration, oldest first. Filename order is application order. */
export const MIGRATIONS: readonly { readonly name: string; readonly migration: Migration }[] = [
${entries}
];
`;
}

/**
 * The project-local runner.
 *
 * Fixed rather than templated: it lists nothing itself — the barrel does — so
 * it has no reason to vary per project, and a fixed file is one a developer can
 * read once and then ignore.
 *
 * It applies migrations in order and stops at the first failure, reporting which
 * one. There is deliberately no ledger of what has already run: that needs a
 * table, which needs a schema, which is the thing being migrated.
 *
 * It is emitted `managed`, so a later `generate migration` rewrites it — which
 * is why the emitted header says so and points a project wanting a ledger at a
 * module of its own that calls `runMigrations`. Saying "this is your file" while
 * overwriting it is the contradiction review caught.
 */
const RUNNER = `// Generated by \`${PROGRAM_NAME} generate migration\`.
// The CLI owns this file and REWRITES it on every \`generate migration\`, so
// edits here are lost. Run it with:
//
//   deno run -A src/migrations/run.ts          # apply every migration
//   deno run -A src/migrations/run.ts --down   # reverse them, newest first
//
// It applies migrations in order and stops at the first failure. It keeps NO
// record of what has already run: that needs a table, which needs a schema,
// which is the thing being migrated. To add one — or any other behaviour — put
// it in a module of your own beside this file and call \`runMigrations\` from
// there; that module is yours and the CLI never touches it.

import { MIGRATIONS } from './index.ts';

/** One reversible schema change. */
export interface Migration {
  /** Applies the change. */
  up(): Promise<void>;
  /** Reverses {@linkcode Migration.up}. */
  down(): Promise<void>;
}

/**
 * Applies or reverses every migration.
 *
 * @param direction - \`up\` applies oldest first; \`down\` reverses newest first
 */
export async function runMigrations(direction: 'up' | 'down' = 'up'): Promise<void> {
  const ordered = direction === 'up' ? MIGRATIONS : [...MIGRATIONS].reverse();

  for (const entry of ordered) {
    try {
      await entry.migration[direction]();
      console.log(\`\${direction} \${entry.name}\`);
    } catch (cause) {
      // Rethrown with the migration named: a bare driver error says which
      // STATEMENT failed and never which migration it came from.
      throw new Error(\`Migration \${entry.name} failed on \${direction}\`, { cause });
    }
  }
}

if (import.meta.main) {
  await runMigrations(Deno.args.includes('--down') ? 'down' : 'up');
}
`;
