/**
 * The aggregate module barrel — the seam that wires generated modules into a
 * project's `setu.config.ts` without editing it.
 *
 * It imports module classes rather than the controller and service classes they
 * contain. The CLI owns activation through this managed file; application code
 * owns each module declaration and can add imports or providers without the
 * generator rewriting it.
 *
 * @module
 */

import { deriveNames } from '../utils/names.ts';
import { renderExportedArray } from '../seams/seam-spec.ts';

/** Barrel export naming every generated module class. */
export const MODULES_EXPORT = 'MODULES';
/** Deprecated compatibility export for configs generated before module declarations. */
export const LEGACY_CONTROLLERS_EXPORT = 'MODULE_CONTROLLERS';
/** Deprecated compatibility export for configs generated before module declarations. */
export const LEGACY_SERVICES_EXPORT = 'MODULE_SERVICES';

/**
 * Renders the aggregate barrel for a set of module directory names.
 *
 * Pure and deterministic: the names are sorted before rendering, so two calls
 * with the same set in a different order produce byte-identical output and a
 * regeneration that changes nothing leaves an empty diff.
 *
 * @param moduleNames - Declared module directory names (kebab-case), in any order
 * @param legacyModuleNames - Old module directories that have no declaration yet
 * @returns The contents of `src/modules/index.ts`
 */
export function renderModuleBarrel(
  moduleNames: readonly string[],
  legacyModuleNames: readonly string[] = [],
): string {
  const sorted = [...new Set(moduleNames)].sort();
  const legacy = [...new Set(legacyModuleNames)].filter((name) => !sorted.includes(name)).sort();
  const all = [...new Set([...sorted, ...legacy])].sort();

  const imports = all
    .map((name) => {
      const { pascal, kebab } = deriveNames(name);
      const declaration = sorted.includes(name)
        ? `import { ${pascal}Module } from './${kebab}/${kebab}.module.ts';\n`
        : '';
      return `import { ${pascal}Controller } from './${kebab}/${kebab}.controller.ts';\n` +
        declaration +
        `import { ${pascal}Service } from './${kebab}/${kebab}.service.ts';`;
    })
    .join('\n');

  const modules = sorted.map((name) => `${deriveNames(name).pascal}Module`);
  const controllers = all.map((name) => `${deriveNames(name).pascal}Controller`);
  const services = all.map((name) => `${deriveNames(name).pascal}Service`);

  return `// Generated by \`setu generate module\`. The CLI owns this file and rewrites it
// whenever a module is added, so edits here are lost — add modules with the CLI.
//
// It lists which modules are ACTIVE. What each contains is declared by its
// own \`@Module\` in \`src/modules/<name>/<name>.module.ts\`, which is yours.
//
// \`setu.config.ts\` passes this array to DecoratorPlugin:
//
//   DecoratorPlugin({ modules: ${MODULES_EXPORT} })
//
// The deprecated controller/service arrays below keep pre-M83 configs working
// while their modules migrate. New configs must use MODULES; do not add those
// deprecated arrays to a new config.

import type { Constructor } from '@setu-ts/common';
${imports === '' ? '' : `\n${imports}\n`}
/** Every generated module class, for \`DecoratorPlugin({ modules })\`. */
${renderExportedArray(MODULES_EXPORT, 'Constructor', modules)}

/** @deprecated Compatibility for configs generated before module declarations. */
${renderExportedArray(LEGACY_CONTROLLERS_EXPORT, 'Constructor', controllers)}

/** @deprecated Compatibility for configs generated before module declarations. */
${renderExportedArray(LEGACY_SERVICES_EXPORT, 'Constructor', services)}
`;
}
