/**
 * The aggregate module barrel — the seam that wires generated modules into a
 * project's `setu.config.ts` without editing it.
 *
 * It imports module classes rather than the controller and service classes they
 * contain. The CLI owns activation through this managed file; application code
 * owns each module declaration and can add imports or providers without the
 * generator rewriting it.
 *
 * @module
 */

import { deriveNames } from '../utils/names.ts';
import { renderExportedArray } from '../seams/seam-spec.ts';

/** Barrel export naming every generated module class. */
export const MODULES_EXPORT = 'MODULES';

/**
 * Renders the aggregate barrel for a set of module directory names.
 *
 * Pure and deterministic: the names are sorted before rendering, so two calls
 * with the same set in a different order produce byte-identical output and a
 * regeneration that changes nothing leaves an empty diff.
 *
 * @param moduleNames - Module directory names (kebab-case), in any order
 * @returns The contents of `src/modules/index.ts`
 */
export function renderModuleBarrel(moduleNames: readonly string[]): string {
  const sorted = [...new Set(moduleNames)].sort();

  const imports = sorted
    .map((name) => {
      const { pascal, kebab } = deriveNames(name);
      return `import { ${pascal}Module } from './${kebab}/${kebab}.module.ts';`;
    })
    .join('\n');

  const modules = sorted.map((name) => `${deriveNames(name).pascal}Module`);

  return `// Generated by \`setu generate module\`. The CLI owns this file and rewrites it
// whenever a module is added, so edits here are lost — add modules with the CLI.
//
// It lists which modules are ACTIVE. What each contains is declared by its
// own \`@Module\` in \`src/modules/<name>/<name>.module.ts\`, which is yours.
//
// \`setu.config.ts\` passes this array to DecoratorPlugin:
//
//   DecoratorPlugin({ modules: ${MODULES_EXPORT} })
//
// If you scaffolded this project before \`setu generate module\` existed, add that
// import and that option to wire generated modules in.

import type { Constructor } from '@setu-ts/common';
${imports === '' ? '' : `\n${imports}\n`}
/** Every generated module class, for \`DecoratorPlugin({ modules })\`. */
${renderExportedArray(MODULES_EXPORT, 'Constructor', modules)}
`;
}
