/**
 * The aggregate module barrel — the seam that wires generated modules into a
 * project's `setu.config.ts` without editing it.
 *
 * A scaffolded config imports `MODULE_CONTROLLERS` and `MODULE_SERVICES` from
 * `src/modules/index.ts` and passes them to `DecoratorPlugin`, so adding a module
 * changes only this file. The CLI generated it and regenerates it, which is why
 * it is emitted as {@linkcode GeneratedFile.managed} — see `utils/file-writer.ts`
 * for why that is a per-file declaration and not a `--force` flag.
 *
 * @module
 */

import { deriveNames } from '../utils/names.ts';

/** Barrel export naming every generated module's controller class. */
export const CONTROLLERS_EXPORT = 'MODULE_CONTROLLERS';

/** Barrel export naming every generated module's service class. */
export const SERVICES_EXPORT = 'MODULE_SERVICES';

/**
 * Renders the aggregate barrel for a set of module directory names.
 *
 * Pure and deterministic: the names are sorted before rendering, so two calls
 * with the same set in a different order produce byte-identical output and a
 * regeneration that changes nothing leaves an empty diff.
 *
 * @param moduleNames - Module directory names (kebab-case), in any order
 * @returns The contents of `src/modules/index.ts`
 */
export function renderModuleBarrel(moduleNames: readonly string[]): string {
  const sorted = [...new Set(moduleNames)].sort();

  const imports = sorted
    .map((name) => {
      const { pascal, kebab } = deriveNames(name);
      return `import { ${pascal}Controller } from './${kebab}/${kebab}.controller.ts';\n` +
        `import { ${pascal}Service } from './${kebab}/${kebab}.service.ts';`;
    })
    .join('\n');

  const controllers = sorted.map((name) => `${deriveNames(name).pascal}Controller`);
  const services = sorted.map((name) => `${deriveNames(name).pascal}Service`);

  return `// Generated by \`setu generate module\`. The CLI owns this file and rewrites it
// whenever a module is added, so edits here are lost — add modules with the CLI.
//
// \`setu.config.ts\` passes both arrays to DecoratorPlugin:
//
//   DecoratorPlugin({ controllers: ${CONTROLLERS_EXPORT}, services: ${SERVICES_EXPORT} })
//
// If you scaffolded this project before \`setu generate module\` existed, add that
// import and those two options to wire generated modules in.

import type { Constructor } from '@setu-ts/common';
${imports === '' ? '' : `\n${imports}\n`}
/** Every generated module's controller, for \`DecoratorPlugin({ controllers })\`. */
export const ${CONTROLLERS_EXPORT}: readonly Constructor[] = [${renderList(controllers)}];

/** Every generated module's service, for \`DecoratorPlugin({ services })\`. */
export const ${SERVICES_EXPORT}: readonly Constructor[] = [${renderList(services)}];
`;
}

/**
 * Renders an array literal's contents, breaking onto indented lines once the
 * single-line form would run long.
 *
 * @param entries - Identifier names
 * @returns The text between the brackets
 */
function renderList(entries: readonly string[]): string {
  if (entries.length === 0) return '';
  const inline = entries.join(', ');
  if (inline.length <= 76) return inline;
  return `\n  ${entries.join(',\n  ')},\n`;
}
