---
# Source: setu-ts/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: setu-setu-ts-discovery
  namespace: setu
  labels:
    helm.sh/chart: setu-ts-0.1.0
    app.kubernetes.io/name: setu-ts
    app.kubernetes.io/instance: setu
    app.kubernetes.io/version: "0.1.0-alpha.10"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: ['discovery.k8s.io']
    resources: ['endpointslices']
    verbs: ['get', 'list', 'watch']
---
# Source: setu-ts/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: setu-setu-ts-discovery
  namespace: setu
  labels:
    helm.sh/chart: setu-ts-0.1.0
    app.kubernetes.io/name: setu-ts
    app.kubernetes.io/instance: setu
    app.kubernetes.io/version: "0.1.0-alpha.10"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: setu-setu-ts-discovery
subjects:
  - kind: ServiceAccount
    name: setu-setu-ts
    namespace: setu
