---
# Source: setu-ts/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: setu-setu-ts
  namespace: setu
  labels:
    helm.sh/chart: setu-ts-0.1.0
    app.kubernetes.io/name: setu-ts
    app.kubernetes.io/instance: setu
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
