/* eslint-disable */
/**
 * Auto-generated SDK client. Do not edit manually.
 *
 * This is a reviewed, deterministic fixture generated by `generateOpenApiClient`.
 * It is used by the e2e test to import and exercise the generated client code.
 */

import type { ClientResponse, IHttpClient } from '../../src/index.ts';

export type User = {
  'id': string;
  'name': string;
  'email'?: string;
};

export interface listUsersArgs {
  options?: {
    page?: number;
    limit?: number;
  };
}

export interface getUserByIdArgs {
  id: string;
}

export interface GeneratedApi {
  listUsers(opts?: Record<string, unknown>): Promise<ClientResponse<User[]>>;
  getUserById(id: string): Promise<ClientResponse<User>>;
}

export function createApi(client: IHttpClient): GeneratedApi {
  function listUsers(opts?: Record<string, unknown>): Promise<ClientResponse<User[]>> {
    return client.request<User[]>({
      method: 'GET',
      path: '/users',
      query: {
        'page': opts?.page as number | undefined,
        'limit': opts?.limit as number | undefined,
      },
    });
  }

  function getUserById(id: string): Promise<ClientResponse<User>> {
    return client.request<User>({
      method: 'GET',
      path: '/users/' + encodeURIComponent(id),
    });
  }

  return {
    listUsers,
    getUserById,
  };
}
